import type { AccessEvent, Appointment, MedicationItem, PatientDocument } from './patient.models';

export const APPOINTMENT_FIXTURES: readonly Appointment[] = [
  {
    id: 'appointment_demo_q7V2mP',
    appointmentTypeId: 'appointment_type_demo_internal',
    centreId: 'centre_demo_atlantic',
    title: 'Consulta de seguimiento',
    professional: 'Dra. Elena Robles',
    specialty: 'Medicina interna',
    centre: 'Centro Atlántico',
    room: 'Consulta 2.14',
    dateIso: '2026-07-23',
    startsAt: '2026-07-23T10:30:00+02:00',
    endsAt: '2026-07-23T11:00:00+02:00',
    dateLabel: 'Jueves, 23 de julio de 2026',
    timeLabel: '10:30–11:00',
    timezone: 'Hora peninsular',
    attendanceMode: 'in-person',
    status: 'scheduled',
    version: 1,
    changeAllowed: true,
    changeDeadline: '2026-07-23T08:30:00+02:00',
    preparation: [
      'Llega 10 minutos antes para completar la admisión.',
      'Lleva un documento identificativo vigente.',
      'Si el centro te envía indicaciones adicionales, aparecerán en este portal.',
    ],
  },
  {
    id: 'appointment_demo_b3K8tN',
    appointmentTypeId: 'appointment_type_demo_family',
    centreId: 'centre_demo_atlantic',
    title: 'Revisión programada',
    professional: 'Dr. Marcos Vega',
    specialty: 'Medicina de familia',
    centre: 'Centro Atlántico',
    room: 'Consulta 1.06',
    dateIso: '2026-05-12',
    startsAt: '2026-05-12T09:00:00+02:00',
    endsAt: '2026-05-12T09:30:00+02:00',
    dateLabel: 'Martes, 12 de mayo de 2026',
    timeLabel: '09:00–09:30',
    timezone: 'Hora peninsular',
    attendanceMode: 'in-person',
    status: 'completed',
    version: 1,
    changeAllowed: false,
    changeDeadline: '2026-05-12T07:00:00+02:00',
    preparation: [],
  },
];

export const MEDICATION_FIXTURES: readonly MedicationItem[] = [
  {
    id: 'medication_demo_t8R3cL',
    name: 'Losartán',
    presentation: '50 mg · comprimidos',
    scheduleLabel: '1 comprimido cada 24 horas (mañana)',
    source: 'professional-record',
    sourceLabel: 'Información facilitada por Centro Atlántico',
    status: 'active',
    canRequestRenewal: true,
    renewalRequestStatus: null,
    lastUpdatedLabel: 'Actualizado el 15 de julio de 2026',
  },
  {
    id: 'medication_demo_w4P9sD',
    name: 'Metformina',
    presentation: '850 mg · comprimidos',
    scheduleLabel: '1 comprimido cada 12 horas (desayuno y cena)',
    source: 'professional-record',
    sourceLabel: 'Información facilitada por Centro Atlántico',
    status: 'active',
    canRequestRenewal: true,
    renewalRequestStatus: null,
    lastUpdatedLabel: 'Actualizado el 15 de julio de 2026',
  },
];

export const DOCUMENT_FIXTURES: readonly PatientDocument[] = [
  {
    id: 'document_demo_x3M7vA',
    title: 'Resumen de atención',
    category: 'care-summary',
    categoryLabel: 'Resumen asistencial',
    dateIso: '2026-07-15',
    dateLabel: '15 de julio de 2026',
    publishedAt: '2026-07-15T10:00:00+02:00',
    centre: 'Centro Atlántico',
    format: 'PDF',
    mimeType: 'application/pdf',
    sizeBytes: 290_816,
    sizeLabel: '284 KB',
    versionNumber: 2,
    integrityStatus: 'verified',
    canDownload: true,
  },
  {
    id: 'document_demo_k9Q2fJ',
    title: 'Resultados de laboratorio',
    category: 'laboratory',
    categoryLabel: 'Laboratorio',
    dateIso: '2026-07-08',
    dateLabel: '8 de julio de 2026',
    publishedAt: '2026-07-08T16:30:00+02:00',
    centre: 'Centro Atlántico',
    format: 'PDF',
    mimeType: 'application/pdf',
    sizeBytes: 200_704,
    sizeLabel: '196 KB',
    versionNumber: 1,
    integrityStatus: 'verified',
    canDownload: true,
  },
  {
    id: 'document_demo_r5C1hV',
    title: 'Consentimiento informado',
    category: 'consent',
    categoryLabel: 'Consentimiento',
    dateIso: '2026-05-02',
    dateLabel: '2 de mayo de 2026',
    publishedAt: '2026-05-02T09:00:00+02:00',
    centre: 'Centro Atlántico',
    format: 'PDF',
    mimeType: 'application/pdf',
    sizeBytes: 145_408,
    sizeLabel: '142 KB',
    versionNumber: 1,
    integrityStatus: 'verified',
    canDownload: true,
  },
];

export const ACCESS_FIXTURES: readonly AccessEvent[] = [
  {
    id: 'access_demo_h6B2nM',
    actorLabel: 'Dra. Elena Robles',
    roleLabel: 'Profesional de medicina interna',
    purposeLabel: 'Atención asistencial programada',
    dateIso: '2026-07-15T09:12:00+02:00',
    dateLabel: '15 de julio de 2026 · 09:12',
    result: 'Legitimate access',
  },
  {
    id: 'access_demo_p4T8yK',
    actorLabel: 'Equipo de enfermería',
    roleLabel: 'Enfermería del Centro Atlántico',
    purposeLabel: 'Preparación de consulta',
    dateIso: '2026-07-14T16:45:00+02:00',
    dateLabel: '14 de julio de 2026 · 16:45',
    result: 'Legitimate access',
  },
  {
    id: 'access_demo_z8L3qS',
    actorLabel: 'Admisión del centro',
    roleLabel: 'Gestión de citas',
    purposeLabel: 'Confirmación de cita',
    dateIso: '2026-07-13T11:30:00+02:00',
    dateLabel: '13 de julio de 2026 · 11:30',
    result: 'Legitimate access',
  },
];
