/**
 * Inventario canónico de mockups de Salud Nexus.
 *
 * `ruta` describe la URL funcional, nunca la URL del catálogo. Las vistas de
 * detalle usan el contexto activo de la sesión y evitan identificadores
 * sanitarios, tokens o datos personales en la URL.
 */

export type ScreenFamily = 'G' | 'P' | 'C' | 'R' | 'A' | 'S' | 'O';

export type ScreenId = `${ScreenFamily}${number}`;

export type ScreenAudience =
  | 'publica'
  | 'paciente'
  | 'representante'
  | 'profesional'
  | 'recepcion'
  | 'administracion'
  | 'seguridad'
  | 'auditoria'
  | 'dpd'
  | 'soporte';

export type VisualStateProfileId =
  'ST-A' | 'ST-B' | 'ST-C' | 'ST-D' | 'ST-E' | 'ST-F' | 'ST-G' | 'ST-H' | 'ST-I' | 'ST-J' | 'ST-K';

export type ResponsiveProfileId =
  'RS-A' | 'RS-P' | 'RS-W' | 'RS-D' | 'RS-C' | 'RS-T' | 'RS-R' | 'RS-X' | 'RS-K' | 'RS-Q';

export type MotionProfileId = 'M0' | 'M1' | 'M2' | 'M3' | 'M4' | 'M5' | 'M6' | 'M7' | 'M8';

export type ScreenPriority = 'critica' | 'alta' | 'media' | 'baja';

export interface VisualStateProfile {
  readonly id: VisualStateProfileId;
  readonly nombre: string;
  readonly variantes: readonly string[];
}

export interface ResponsiveProfile {
  readonly id: ResponsiveProfileId;
  readonly nombre: string;
  readonly comportamiento: string;
}

export interface MotionProfile {
  readonly id: MotionProfileId;
  readonly nombre: string;
  readonly comportamiento: string;
  readonly movimientoReducido: string;
}

export interface ScreenDefinition {
  readonly id: ScreenId;
  readonly audiencia: readonly ScreenAudience[];
  readonly ruta: string;
  readonly titulo: string;
  readonly descripcion: string;
  readonly estadoVisual: VisualStateProfileId;
  readonly responsive: ResponsiveProfileId;
  readonly motion: MotionProfileId;
  readonly prioridad: ScreenPriority;
}

export const visualStateProfiles = [
  {
    id: 'ST-A',
    nombre: 'Contenido operativo',
    variantes: ['poblado', 'carga', 'vacío', 'error recuperable'],
  },
  {
    id: 'ST-B',
    nombre: 'Carga y sincronización',
    variantes: ['skeleton', 'latencia alta', 'reintento', 'actualizado'],
  },
  {
    id: 'ST-C',
    nombre: 'Primera vez o sin resultados',
    variantes: ['sin datos', 'sin coincidencias', 'filtros activos', 'acción sugerida'],
  },
  {
    id: 'ST-D',
    nombre: 'Formulario y validación',
    variantes: ['inicial', 'error por campo', 'error global', 'guardado'],
  },
  {
    id: 'ST-E',
    nombre: 'Acceso restringido',
    variantes: ['sin permiso', 'sin relación asistencial', 'restricción activa', 'sesión caducada'],
  },
  {
    id: 'ST-F',
    nombre: 'Servicio degradado',
    variantes: ['sin conexión', 'solo lectura', 'dependencia no disponible', 'recuperado'],
  },
  {
    id: 'ST-G',
    nombre: 'Acción sensible',
    variantes: ['alcance', 'reautenticación', 'doble control', 'cancelada'],
  },
  {
    id: 'ST-H',
    nombre: 'Conflicto concurrente',
    variantes: ['versión obsoleta', 'recurso ocupado', 'comparación', 'resuelto'],
  },
  {
    id: 'ST-I',
    nombre: 'Proceso asíncrono',
    variantes: ['en cola', 'procesando', 'parcial', 'fallido', 'completado'],
  },
  {
    id: 'ST-J',
    nombre: 'Resultado irreversible',
    variantes: ['confirmación final', 'éxito', 'revocado', 'evidencia'],
  },
  {
    id: 'ST-K',
    nombre: 'Acceso excepcional',
    variantes: ['justificación', 'alcance temporal', 'sesión activa', 'revisión posterior'],
  },
] as const satisfies readonly VisualStateProfile[];

export const responsiveProfiles = [
  {
    id: 'RS-A',
    nombre: 'Acceso',
    comportamiento: 'Una columna enfocada; panel de ayuda secundario desde 960 px.',
  },
  {
    id: 'RS-P',
    nombre: 'Paciente móvil',
    comportamiento:
      'Acción principal fija y navegación inferior; dos columnas solo cuando mejora la lectura.',
  },
  {
    id: 'RS-W',
    nombre: 'Puesto clínico',
    comportamiento: 'Cabecera de contexto persistente, rail adaptable y panel auxiliar colapsable.',
  },
  {
    id: 'RS-D',
    nombre: 'Datos densos',
    comportamiento: 'Tabla en escritorio; lista semántica y filtros en hoja lateral en móvil.',
  },
  {
    id: 'RS-C',
    nombre: 'Calendario',
    comportamiento:
      'Día en móvil, semana adaptable y mes solo en anchuras amplias; alternativa sin arrastre.',
  },
  {
    id: 'RS-T',
    nombre: 'Timeline',
    comportamiento: 'Cronología lineal en móvil y detalle contextual paralelo en escritorio.',
  },
  {
    id: 'RS-R',
    nombre: 'Informe',
    comportamiento: 'Filtros plegables, visualización fluida y tabla accesible equivalente.',
  },
  {
    id: 'RS-X',
    nombre: 'Público o quiosco',
    comportamiento:
      'Objetivos táctiles amplios, privacidad física y reinicio automático de contexto.',
  },
  {
    id: 'RS-K',
    nombre: 'Operación crítica',
    comportamiento:
      'Alcance y consecuencias siempre visibles; confirmación separada de la navegación.',
  },
  {
    id: 'RS-Q',
    nombre: 'Overlay',
    comportamiento:
      'Diálogo en escritorio y hoja inferior de altura segura en móvil, con foco contenido.',
  },
] as const satisfies readonly ResponsiveProfile[];

export const motionProfiles = [
  {
    id: 'M0',
    nombre: 'Sin movimiento',
    comportamiento: 'Cambio inmediato para tareas clínicas repetitivas o información crítica.',
    movimientoReducido: 'Sin cambios.',
  },
  {
    id: 'M1',
    nombre: 'Entrada discreta',
    comportamiento: 'Opacidad y desplazamiento de 4 px durante 140–180 ms.',
    movimientoReducido: 'Solo opacidad o cambio inmediato.',
  },
  {
    id: 'M2',
    nombre: 'Lista progresiva',
    comportamiento: 'Stagger máximo de seis elementos, 25 ms entre ellos.',
    movimientoReducido: 'Entrada simultánea sin desplazamiento.',
  },
  {
    id: 'M3',
    nombre: 'Paso guiado',
    comportamiento: 'Transición direccional de 180–220 ms que conserva foco y progreso.',
    movimientoReducido: 'Sustitución inmediata y anuncio del paso.',
  },
  {
    id: 'M4',
    nombre: 'Cambio de estado',
    comportamiento: 'Microinteracción de icono y color durante 120–180 ms.',
    movimientoReducido: 'Cambio de texto e icono sin interpolación.',
  },
  {
    id: 'M5',
    nombre: 'Overlay',
    comportamiento: 'Entrada por escala u hoja inferior durante 160–220 ms.',
    movimientoReducido: 'Aparición inmediata manteniendo retorno de foco.',
  },
  {
    id: 'M6',
    nombre: 'Cronología',
    comportamiento: 'Revelado por bloques al navegar, nunca ligado de forma continua al scroll.',
    movimientoReducido: 'Todos los bloques visibles.',
  },
  {
    id: 'M7',
    nombre: 'Narrativa ScrollFX',
    comportamiento:
      'ScrollTrigger solo en onboarding o explicación de privacidad, con transform y opacidad.',
    movimientoReducido: 'Contenido estático completo y sin pinning.',
  },
  {
    id: 'M8',
    nombre: 'Dato en vivo',
    comportamiento: 'Pulso único no bloqueante al recibir una actualización relevante.',
    movimientoReducido: 'Etiqueta textual «Actualizado».',
  },
] as const satisfies readonly MotionProfile[];

export const screenCatalog = [
  {
    id: 'G01',
    audiencia: ['publica'],
    ruta: '/',
    titulo: 'Inicio seguro',
    descripcion:
      'Presenta la plataforma, sus límites asistenciales y los accesos para paciente y personal.',
    estadoVisual: 'ST-A',
    responsive: 'RS-A',
    motion: 'M7',
    prioridad: 'alta',
  },
  {
    id: 'G02',
    audiencia: ['publica'],
    ruta: '/auth/iniciar-sesion',
    titulo: 'Iniciar sesión',
    descripcion: 'Acceso único con identificación, passkey u OIDC y mensajes anti-enumeración.',
    estadoVisual: 'ST-D',
    responsive: 'RS-A',
    motion: 'M1',
    prioridad: 'critica',
  },
  {
    id: 'G03',
    audiencia: ['publica'],
    ruta: '/auth/verificar-segundo-factor',
    titulo: 'Verificar segundo factor',
    descripcion: 'Reto MFA con método alternativo, códigos de recuperación y bloqueo progresivo.',
    estadoVisual: 'ST-D',
    responsive: 'RS-A',
    motion: 'M3',
    prioridad: 'critica',
  },
  {
    id: 'G04',
    audiencia: ['paciente', 'profesional', 'seguridad'],
    ruta: '/auth/configurar-passkey',
    titulo: 'Configurar passkey',
    descripcion:
      'Alta guiada de credencial resistente a phishing con nombre de dispositivo y recuperación.',
    estadoVisual: 'ST-G',
    responsive: 'RS-A',
    motion: 'M3',
    prioridad: 'alta',
  },
  {
    id: 'G05',
    audiencia: ['publica'],
    ruta: '/auth/recuperar-acceso',
    titulo: 'Recuperar acceso',
    descripcion: 'Inicio de recuperación con respuesta uniforme y canal verificado.',
    estadoVisual: 'ST-D',
    responsive: 'RS-A',
    motion: 'M1',
    prioridad: 'critica',
  },
  {
    id: 'G06',
    audiencia: ['publica'],
    ruta: '/auth/recuperar-acceso/verificar',
    titulo: 'Verificar recuperación',
    descripcion: 'Comprobación reforzada con caducidad, intentos limitados y ayuda segura.',
    estadoVisual: 'ST-D',
    responsive: 'RS-A',
    motion: 'M3',
    prioridad: 'critica',
  },
  {
    id: 'G07',
    audiencia: ['publica'],
    ruta: '/auth/restablecer-credencial',
    titulo: 'Restablecer credencial',
    descripcion: 'Define una nueva credencial, revoca sesiones previas y confirma el cambio.',
    estadoVisual: 'ST-J',
    responsive: 'RS-A',
    motion: 'M3',
    prioridad: 'critica',
  },
  {
    id: 'G08',
    audiencia: ['publica', 'paciente', 'representante'],
    ruta: '/legal/privacidad',
    titulo: 'Información de privacidad',
    descripcion:
      'Explica finalidades, bases jurídicas, derechos y canales del DPD en lenguaje claro.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M7',
    prioridad: 'alta',
  },
  {
    id: 'G09',
    audiencia: ['publica'],
    ruta: '/legal/accesibilidad',
    titulo: 'Declaración de accesibilidad',
    descripcion:
      'Publica nivel de conformidad, limitaciones conocidas y canal de comunicación accesible.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M1',
    prioridad: 'media',
  },
  {
    id: 'G10',
    audiencia: [
      'paciente',
      'representante',
      'profesional',
      'recepcion',
      'administracion',
      'seguridad',
    ],
    ruta: '/sesion/proxima-a-caducar',
    titulo: 'Sesión próxima a caducar',
    descripcion: 'Avisa con tiempo restante y permite continuar tras verificación cuando procede.',
    estadoVisual: 'ST-G',
    responsive: 'RS-Q',
    motion: 'M5',
    prioridad: 'critica',
  },
  {
    id: 'G11',
    audiencia: [
      'paciente',
      'representante',
      'profesional',
      'recepcion',
      'administracion',
      'seguridad',
    ],
    ruta: '/sesion/caducada',
    titulo: 'Sesión caducada',
    descripcion:
      'Confirma limpieza de contexto y ofrece reautenticación sin revelar contenido previo.',
    estadoVisual: 'ST-E',
    responsive: 'RS-A',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'G12',
    audiencia: [
      'paciente',
      'representante',
      'profesional',
      'recepcion',
      'administracion',
      'seguridad',
    ],
    ruta: '/sin-permiso',
    titulo: 'Acceso no autorizado',
    descripcion:
      'Explica la denegación sin revelar existencia del recurso y ofrece una salida segura.',
    estadoVisual: 'ST-E',
    responsive: 'RS-A',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'G13',
    audiencia: ['publica'],
    ruta: '/no-encontrado',
    titulo: 'Página no encontrada',
    descripcion:
      'Recupera la navegación sin distinguir entre recursos inexistentes y no autorizados.',
    estadoVisual: 'ST-C',
    responsive: 'RS-A',
    motion: 'M1',
    prioridad: 'media',
  },
  {
    id: 'G14',
    audiencia: ['paciente', 'representante', 'profesional', 'recepcion', 'administracion'],
    ruta: '/sin-conexion',
    titulo: 'Sin conexión',
    descripcion:
      'Informa qué acciones no están disponibles y evita conservar datos clínicos localmente.',
    estadoVisual: 'ST-F',
    responsive: 'RS-A',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'G15',
    audiencia: ['paciente', 'representante', 'profesional', 'recepcion', 'administracion'],
    ruta: '/servicio-degradado',
    titulo: 'Servicio degradado',
    descripcion:
      'Diferencia funciones operativas, solo lectura y dependencias temporalmente indisponibles.',
    estadoVisual: 'ST-F',
    responsive: 'RS-A',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'G16',
    audiencia: ['publica'],
    ruta: '/mantenimiento',
    titulo: 'Mantenimiento programado',
    descripcion: 'Comunica ventana, estado y canales alternativos sin exponer infraestructura.',
    estadoVisual: 'ST-F',
    responsive: 'RS-A',
    motion: 'M1',
    prioridad: 'media',
  },
  {
    id: 'G17',
    audiencia: ['profesional', 'recepcion', 'administracion', 'seguridad', 'auditoria', 'dpd'],
    ruta: '/contexto-operativo',
    titulo: 'Elegir contexto operativo',
    descripcion:
      'Muestra el centro fijo y selecciona unidad, servicio, rol y finalidad autorizados.',
    estadoVisual: 'ST-D',
    responsive: 'RS-W',
    motion: 'M3',
    prioridad: 'critica',
  },
  {
    id: 'G18',
    audiencia: ['paciente', 'representante', 'profesional', 'recepcion', 'administracion'],
    ruta: '/notificaciones',
    titulo: 'Centro de notificaciones',
    descripcion: 'Agrupa avisos no clínicos con lectura, prioridad, caducidad y acciones seguras.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M2',
    prioridad: 'media',
  },
  {
    id: 'G19',
    audiencia: ['publica', 'paciente', 'representante', 'profesional', 'recepcion'],
    ruta: '/ayuda',
    titulo: 'Ayuda y límites del servicio',
    descripcion:
      'Ofrece soporte, accesibilidad y orientación urgente indicando que no sustituye emergencias.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M1',
    prioridad: 'alta',
  },
  {
    id: 'G20',
    audiencia: ['paciente', 'representante', 'profesional', 'recepcion', 'administracion'],
    ruta: '/preferencias/accesibilidad',
    titulo: 'Preferencias de accesibilidad',
    descripcion: 'Configura contraste, tamaño, densidad y movimiento sin reducir la semántica.',
    estadoVisual: 'ST-D',
    responsive: 'RS-P',
    motion: 'M0',
    prioridad: 'media',
  },

  {
    id: 'P01',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/inicio',
    titulo: 'Inicio del paciente',
    descripcion: 'Resume próximas acciones, citas, documentos y avisos con una prioridad clara.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M2',
    prioridad: 'critica',
  },
  {
    id: 'P02',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/bienvenida',
    titulo: 'Bienvenida y alcance',
    descripcion: 'Explica qué puede gestionar el portal y qué debe resolverse con el centro.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M7',
    prioridad: 'alta',
  },
  {
    id: 'P03',
    audiencia: ['paciente'],
    ruta: '/paciente/alta/verificar-identidad',
    titulo: 'Verificar identidad',
    descripcion:
      'Valida identidad y evidencia de alta sin convertir el flujo en una búsqueda enumerable.',
    estadoVisual: 'ST-D',
    responsive: 'RS-P',
    motion: 'M3',
    prioridad: 'critica',
  },
  {
    id: 'P04',
    audiencia: ['paciente'],
    ruta: '/paciente/alta/contacto',
    titulo: 'Confirmar contacto',
    descripcion:
      'Verifica canales de contacto y separa datos administrativos de información sanitaria.',
    estadoVisual: 'ST-D',
    responsive: 'RS-P',
    motion: 'M3',
    prioridad: 'alta',
  },
  {
    id: 'P05',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/alta/preferencias',
    titulo: 'Configurar experiencia',
    descripcion: 'Recoge idioma, accesibilidad y canal preferido con consentimiento granular.',
    estadoVisual: 'ST-D',
    responsive: 'RS-P',
    motion: 'M3',
    prioridad: 'media',
  },
  {
    id: 'P06',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/perfil',
    titulo: 'Perfil',
    descripcion:
      'Muestra identidad, contacto, centro de referencia y datos editables según alcance.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M1',
    prioridad: 'alta',
  },
  {
    id: 'P07',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/perfil/contacto',
    titulo: 'Editar contacto',
    descripcion: 'Actualiza teléfono, correo y dirección con verificación y trazabilidad.',
    estadoVisual: 'ST-D',
    responsive: 'RS-P',
    motion: 'M3',
    prioridad: 'alta',
  },
  {
    id: 'P08',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/perfil/preferencias',
    titulo: 'Preferencias personales',
    descripcion: 'Gestiona idioma, zona horaria y canales sin mezclar consentimientos legales.',
    estadoVisual: 'ST-D',
    responsive: 'RS-P',
    motion: 'M1',
    prioridad: 'media',
  },
  {
    id: 'P09',
    audiencia: ['paciente'],
    ruta: '/paciente/representantes',
    titulo: 'Representantes y personas autorizadas',
    descripcion: 'Lista relaciones, alcance, vigencia y estado de cada representación.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M2',
    prioridad: 'alta',
  },
  {
    id: 'P10',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/representantes/detalle',
    titulo: 'Detalle de representación',
    descripcion: 'Explica facultades, límites, evidencia y proceso de revocación.',
    estadoVisual: 'ST-G',
    responsive: 'RS-P',
    motion: 'M1',
    prioridad: 'alta',
  },
  {
    id: 'P11',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/seguridad/sesiones',
    titulo: 'Sesiones activas',
    descripcion: 'Muestra dispositivo, momento, ubicación aproximada y permite revocación remota.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M2',
    prioridad: 'alta',
  },
  {
    id: 'P12',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/seguridad',
    titulo: 'Seguridad de la cuenta',
    descripcion: 'Gestiona passkeys, MFA, recuperación y actividad de seguridad.',
    estadoVisual: 'ST-G',
    responsive: 'RS-P',
    motion: 'M1',
    prioridad: 'critica',
  },
  {
    id: 'P13',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/citas/proximas',
    titulo: 'Próximas citas',
    descripcion: 'Lista citas futuras con estado, centro, modalidad y siguiente acción.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M2',
    prioridad: 'critica',
  },
  {
    id: 'P14',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/citas/anteriores',
    titulo: 'Citas anteriores',
    descripcion:
      'Consulta historial administrativo filtrable sin mostrar información clínica adicional.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M2',
    prioridad: 'alta',
  },
  {
    id: 'P15',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/citas/detalle',
    titulo: 'Detalle de cita',
    descripcion:
      'Reúne horario, centro, profesional, preparación, documentos y acciones permitidas.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M1',
    prioridad: 'critica',
  },
  {
    id: 'P16',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/citas/nueva/servicio',
    titulo: 'Elegir servicio',
    descripcion: 'Primer paso de reserva con descripciones claras y criterios de elegibilidad.',
    estadoVisual: 'ST-C',
    responsive: 'RS-P',
    motion: 'M3',
    prioridad: 'critica',
  },
  {
    id: 'P17',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/citas/nueva/preferencias',
    titulo: 'Preferencias de atención',
    descripcion: 'Indica modalidad y necesidades de accesibilidad dentro del centro configurado.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M3',
    prioridad: 'alta',
  },
  {
    id: 'P18',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/citas/nueva/profesional',
    titulo: 'Elegir profesional',
    descripcion: 'Permite preferencia o primera disponibilidad sin exponer agendas completas.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M3',
    prioridad: 'media',
  },
  {
    id: 'P19',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/citas/nueva/fecha',
    titulo: 'Elegir fecha',
    descripcion: 'Navega disponibilidad por día con zona horaria y accesibilidad de calendario.',
    estadoVisual: 'ST-B',
    responsive: 'RS-C',
    motion: 'M3',
    prioridad: 'critica',
  },
  {
    id: 'P20',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/citas/nueva/hora',
    titulo: 'Elegir hora',
    descripcion: 'Muestra huecos devueltos por servidor y mantiene una reserva temporal visible.',
    estadoVisual: 'ST-H',
    responsive: 'RS-P',
    motion: 'M4',
    prioridad: 'critica',
  },
  {
    id: 'P21',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/citas/nueva/revisar',
    titulo: 'Revisar reserva',
    descripcion: 'Confirma servicio, hora, modalidad, requisitos y preferencias antes de reservar.',
    estadoVisual: 'ST-G',
    responsive: 'RS-P',
    motion: 'M3',
    prioridad: 'critica',
  },
  {
    id: 'P22',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/citas/nueva/resultado',
    titulo: 'Reserva completada',
    descripcion: 'Entrega confirmación, referencia opaca y siguientes pasos sin duplicar envíos.',
    estadoVisual: 'ST-J',
    responsive: 'RS-P',
    motion: 'M4',
    prioridad: 'critica',
  },
  {
    id: 'P23',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/citas/cambiar',
    titulo: 'Cambiar cita',
    descripcion: 'Selecciona un hueco alternativo conservando la cita original hasta confirmar.',
    estadoVisual: 'ST-H',
    responsive: 'RS-C',
    motion: 'M3',
    prioridad: 'critica',
  },
  {
    id: 'P24',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/citas/cancelar',
    titulo: 'Cancelar cita',
    descripcion: 'Expone consecuencias, política, motivo opcional y alternativa de cambio.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'P25',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/citas/confirmar',
    titulo: 'Confirmar asistencia',
    descripcion: 'Registra confirmación idempotente y muestra el nuevo estado de la cita.',
    estadoVisual: 'ST-J',
    responsive: 'RS-P',
    motion: 'M4',
    prioridad: 'alta',
  },
  {
    id: 'P26',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/citas/preparar-llegada',
    titulo: 'Preparar llegada',
    descripcion: 'Revisa instrucciones, accesibilidad, documentación y condiciones de check-in.',
    estadoVisual: 'ST-D',
    responsive: 'RS-P',
    motion: 'M3',
    prioridad: 'alta',
  },
  {
    id: 'P27',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/citas/documentacion-necesaria',
    titulo: 'Documentación necesaria',
    descripcion: 'Lista requisitos documentales, estado y canal seguro de aportación.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M2',
    prioridad: 'alta',
  },
  {
    id: 'P28',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/citas/anadir-calendario',
    titulo: 'Añadir al calendario',
    descripcion: 'Permite exportar un evento minimizado sin datos clínicos ni tokens.',
    estadoVisual: 'ST-G',
    responsive: 'RS-Q',
    motion: 'M5',
    prioridad: 'media',
  },
  {
    id: 'P29',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/lista-espera/nueva',
    titulo: 'Unirse a lista de espera',
    descripcion:
      'Configura disponibilidad, profesionales y canales antes de confirmar la solicitud.',
    estadoVisual: 'ST-D',
    responsive: 'RS-P',
    motion: 'M3',
    prioridad: 'alta',
  },
  {
    id: 'P30',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/lista-espera',
    titulo: 'Mis listas de espera',
    descripcion: 'Muestra posición informativa, criterios, vigencia y opción de retirada.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M2',
    prioridad: 'alta',
  },
  {
    id: 'P31',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/lista-espera/oferta',
    titulo: 'Oferta de cita liberada',
    descripcion: 'Presenta hora, plazo y acciones aceptar o rechazar sin presión ambigua.',
    estadoVisual: 'ST-H',
    responsive: 'RS-K',
    motion: 'M4',
    prioridad: 'critica',
  },
  {
    id: 'P32',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/citas/solicitar-cambio',
    titulo: 'Solicitar cambio',
    descripcion: 'Registra una petición cuando no existe cambio automático disponible.',
    estadoVisual: 'ST-I',
    responsive: 'RS-P',
    motion: 'M3',
    prioridad: 'alta',
  },
  {
    id: 'P33',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/medicacion/activa',
    titulo: 'Medicación activa',
    descripcion:
      'Distingue información validada, declarada y pendiente de revisión con mínima exposición.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M2',
    prioridad: 'critica',
  },
  {
    id: 'P34',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/medicacion/detalle',
    titulo: 'Detalle de medicación',
    descripcion: 'Muestra pauta, estado, origen, vigencia, advertencias y documentos asociados.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M1',
    prioridad: 'critica',
  },
  {
    id: 'P35',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/medicacion/plan',
    titulo: 'Plan de toma',
    descripcion: 'Ordena horarios y pautas informativas sin emitir recomendaciones terapéuticas.',
    estadoVisual: 'ST-A',
    responsive: 'RS-T',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'P36',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/medicacion/declarar',
    titulo: 'Declarar medicación',
    descripcion: 'Recoge lo comunicado por el paciente y lo etiqueta como no validado.',
    estadoVisual: 'ST-D',
    responsive: 'RS-P',
    motion: 'M3',
    prioridad: 'critica',
  },
  {
    id: 'P37',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/medicacion/no-toma',
    titulo: 'Indicar que no la está tomando',
    descripcion:
      'Registra una declaración y dirige a revisión profesional sin alterar el registro clínico.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'P38',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/medicacion/renovacion/nueva',
    titulo: 'Solicitar renovación',
    descripcion: 'Envía una solicitud informativa con motivo, alcance y expectativas de respuesta.',
    estadoVisual: 'ST-D',
    responsive: 'RS-P',
    motion: 'M3',
    prioridad: 'alta',
  },
  {
    id: 'P39',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/medicacion/renovacion/detalle',
    titulo: 'Seguimiento de renovación',
    descripcion: 'Muestra estado, mensajes administrativos y resolución de la solicitud.',
    estadoVisual: 'ST-I',
    responsive: 'RS-T',
    motion: 'M6',
    prioridad: 'alta',
  },
  {
    id: 'P40',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/medicacion/historica',
    titulo: 'Medicación suspendida o histórica',
    descripcion:
      'Consulta registros inactivos con fechas, fuente y motivo visible cuando está autorizado.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M2',
    prioridad: 'alta',
  },
  {
    id: 'P41',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/medicacion/discrepancias',
    titulo: 'Discrepancias de medicación',
    descripcion:
      'Explica diferencias detectadas y el estado de revisión sin concluir clínicamente.',
    estadoVisual: 'ST-E',
    responsive: 'RS-P',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'P42',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/medicacion/descargar-resumen',
    titulo: 'Descargar resumen de medicación',
    descripcion: 'Confirma formato, alcance y finalidad antes de generar un documento seguro.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'P43',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/medicacion/documentos',
    titulo: 'Documentos de medicación',
    descripcion: 'Relaciona documentos publicados con acceso y descarga auditados.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M2',
    prioridad: 'alta',
  },
  {
    id: 'P44',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/documentos',
    titulo: 'Mis documentos',
    descripcion: 'Lista documentos del centro por categoría, fecha y estado de publicación.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M2',
    prioridad: 'critica',
  },
  {
    id: 'P45',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/documentos/buscar',
    titulo: 'Buscar documentos',
    descripcion: 'Filtra en servidor con criterios claros, sin precargar el archivo completo.',
    estadoVisual: 'ST-C',
    responsive: 'RS-D',
    motion: 'M1',
    prioridad: 'alta',
  },
  {
    id: 'P46',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/documentos/detalle',
    titulo: 'Detalle de documento',
    descripcion: 'Muestra metadatos, versión, firma, publicación y acciones autorizadas.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M1',
    prioridad: 'critica',
  },
  {
    id: 'P47',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/documentos/descargar',
    titulo: 'Descarga segura',
    descripcion: 'Renueva autorización y entrega un archivo temporal con registro de acceso.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'P48',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/documentos/descarga-agrupada',
    titulo: 'Descarga agrupada',
    descripcion: 'Resume número, categorías, finalidad y proceso asíncrono antes de exportar.',
    estadoVisual: 'ST-I',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'P49',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/documentos/solicitud/nueva',
    titulo: 'Solicitar documentación',
    descripcion: 'Crea una petición con alcance, finalidad, formato y canal de entrega.',
    estadoVisual: 'ST-D',
    responsive: 'RS-P',
    motion: 'M3',
    prioridad: 'alta',
  },
  {
    id: 'P50',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/documentos/correccion/nueva',
    titulo: 'Solicitar corrección documental',
    descripcion: 'Describe la corrección, adjunta evidencia y preserva el documento original.',
    estadoVisual: 'ST-D',
    responsive: 'RS-P',
    motion: 'M3',
    prioridad: 'alta',
  },
  {
    id: 'P51',
    audiencia: ['publica', 'paciente'],
    ruta: '/verificar-documento',
    titulo: 'Verificar documento',
    descripcion: 'Permite introducir un código opaco y devuelve únicamente validez mínima.',
    estadoVisual: 'ST-D',
    responsive: 'RS-X',
    motion: 'M1',
    prioridad: 'alta',
  },
  {
    id: 'P52',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/documentos/versiones',
    titulo: 'Versiones del documento',
    descripcion: 'Expone sustituciones, retiradas y versión vigente sin sobrescribir evidencias.',
    estadoVisual: 'ST-A',
    responsive: 'RS-T',
    motion: 'M6',
    prioridad: 'alta',
  },
  {
    id: 'P53',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/privacidad',
    titulo: 'Centro de privacidad',
    descripcion: 'Reúne accesos, derechos, restricciones, consentimientos y descargas de datos.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M7',
    prioridad: 'critica',
  },
  {
    id: 'P54',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/privacidad/accesos',
    titulo: 'Historial de accesos',
    descripcion: 'Muestra quién o qué categoría accedió, cuándo, finalidad y excepcionalidad.',
    estadoVisual: 'ST-A',
    responsive: 'RS-T',
    motion: 'M6',
    prioridad: 'critica',
  },
  {
    id: 'P55',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/privacidad/accesos/detalle',
    titulo: 'Detalle de acceso',
    descripcion: 'Explica alcance, centro, finalidad y vía para solicitar aclaración.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M1',
    prioridad: 'alta',
  },
  {
    id: 'P56',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/privacidad/derechos',
    titulo: 'Solicitudes de derechos',
    descripcion: 'Lista acceso, rectificación, limitación y portabilidad con plazos y estados.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M2',
    prioridad: 'critica',
  },
  {
    id: 'P57',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/privacidad/derechos/nueva',
    titulo: 'Ejercer un derecho',
    descripcion: 'Guía el tipo, alcance, identidad, canal y evidencia necesaria.',
    estadoVisual: 'ST-D',
    responsive: 'RS-P',
    motion: 'M3',
    prioridad: 'critica',
  },
  {
    id: 'P58',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/privacidad/derechos/detalle',
    titulo: 'Seguimiento de solicitud',
    descripcion: 'Presenta cronología, comunicaciones, plazo y documentos de resolución.',
    estadoVisual: 'ST-I',
    responsive: 'RS-T',
    motion: 'M6',
    prioridad: 'alta',
  },
  {
    id: 'P59',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/privacidad/restricciones',
    titulo: 'Restricciones de acceso',
    descripcion: 'Explica restricciones activas, alcance, consecuencias y excepciones legales.',
    estadoVisual: 'ST-E',
    responsive: 'RS-P',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'P60',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/privacidad/restricciones/cambiar',
    titulo: 'Cambiar una restricción',
    descripcion: 'Solicita alcance y confirmación reforzada antes de registrar la decisión.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'P61',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/privacidad/portabilidad',
    titulo: 'Portabilidad de datos',
    descripcion:
      'Define conjunto, formato, destinatario y entrega segura mediante proceso auditado.',
    estadoVisual: 'ST-I',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'P62',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/privacidad/avisos',
    titulo: 'Avisos y decisiones de privacidad',
    descripcion: 'Conserva versiones de textos mostrados y decisiones registradas.',
    estadoVisual: 'ST-A',
    responsive: 'RS-T',
    motion: 'M6',
    prioridad: 'alta',
  },
  {
    id: 'P63',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/comunicaciones',
    titulo: 'Bandeja de comunicaciones',
    descripcion: 'Agrupa mensajes administrativos con filtros, lectura y archivo.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M2',
    prioridad: 'alta',
  },
  {
    id: 'P64',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/comunicaciones/detalle',
    titulo: 'Detalle de comunicación',
    descripcion: 'Muestra el hilo permitido, adjuntos seguros y aviso de no emergencias.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M1',
    prioridad: 'alta',
  },
  {
    id: 'P65',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/comunicaciones/preferencias',
    titulo: 'Preferencias de notificación',
    descripcion: 'Configura canal por categoría con verificación y contenido siempre minimizado.',
    estadoVisual: 'ST-D',
    responsive: 'RS-P',
    motion: 'M1',
    prioridad: 'alta',
  },
  {
    id: 'P66',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/comunicaciones/envios',
    titulo: 'Historial de notificaciones',
    descripcion: 'Indica canal, fecha y resultado sin reproducir contenido sanitario.',
    estadoVisual: 'ST-A',
    responsive: 'RS-P',
    motion: 'M2',
    prioridad: 'media',
  },
  {
    id: 'P67',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/soporte/nueva',
    titulo: 'Nueva solicitud de soporte',
    descripcion: 'Clasifica la necesidad, limita adjuntos y muestra plazo estimado.',
    estadoVisual: 'ST-D',
    responsive: 'RS-P',
    motion: 'M3',
    prioridad: 'alta',
  },
  {
    id: 'P68',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/soporte/detalle',
    titulo: 'Seguimiento de soporte',
    descripcion: 'Presenta estado, mensajes, SLA y resolución sin canal clínico improvisado.',
    estadoVisual: 'ST-I',
    responsive: 'RS-T',
    motion: 'M6',
    prioridad: 'alta',
  },
  {
    id: 'P69',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/ayuda/urgente',
    titulo: 'Necesito ayuda ahora',
    descripcion: 'Distingue soporte del portal, atención sanitaria y emergencias con rutas claras.',
    estadoVisual: 'ST-A',
    responsive: 'RS-X',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'P70',
    audiencia: ['paciente', 'representante'],
    ruta: '/paciente/seguridad/actividad',
    titulo: 'Actividad de seguridad',
    descripcion: 'Muestra cambios de acceso, recuperaciones, revocaciones y alertas de cuenta.',
    estadoVisual: 'ST-A',
    responsive: 'RS-T',
    motion: 'M6',
    prioridad: 'alta',
  },

  {
    id: 'C01',
    audiencia: ['profesional'],
    ruta: '/profesional/inicio',
    titulo: 'Inicio profesional',
    descripcion: 'Prioriza jornada, alertas operativas, pacientes en espera y tareas pendientes.',
    estadoVisual: 'ST-A',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'C02',
    audiencia: ['profesional'],
    ruta: '/profesional/agenda/dia',
    titulo: 'Agenda diaria',
    descripcion: 'Vista densa por hora, estado, modalidad, recurso y acciones por teclado.',
    estadoVisual: 'ST-A',
    responsive: 'RS-C',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'C03',
    audiencia: ['profesional'],
    ruta: '/profesional/agenda/semana',
    titulo: 'Agenda semanal',
    descripcion: 'Compara carga y disponibilidad con alternativa accesible a la cuadrícula.',
    estadoVisual: 'ST-A',
    responsive: 'RS-C',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'C04',
    audiencia: ['profesional'],
    ruta: '/profesional/agenda/mes',
    titulo: 'Agenda mensual',
    descripcion: 'Resume ocupación y excepciones sin ocultar conflictos ni estados.',
    estadoVisual: 'ST-A',
    responsive: 'RS-C',
    motion: 'M0',
    prioridad: 'media',
  },
  {
    id: 'C05',
    audiencia: ['profesional'],
    ruta: '/profesional/agenda/recursos',
    titulo: 'Agenda por recurso',
    descripcion: 'Coordina consulta, sala y equipamiento con conflictos multi-recurso.',
    estadoVisual: 'ST-H',
    responsive: 'RS-C',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'C06',
    audiencia: ['profesional'],
    ruta: '/profesional/citas/detalle',
    titulo: 'Detalle profesional de cita',
    descripcion: 'Reúne contexto mínimo, participantes, recursos y transiciones autorizadas.',
    estadoVisual: 'ST-A',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'C07',
    audiencia: ['profesional'],
    ruta: '/profesional/citas/cambiar-estado',
    titulo: 'Cambiar estado de cita',
    descripcion: 'Expone únicamente transiciones válidas y registra motivo cuando corresponde.',
    estadoVisual: 'ST-G',
    responsive: 'RS-Q',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'C08',
    audiencia: ['profesional'],
    ruta: '/profesional/citas/finalizar',
    titulo: 'Finalizar cita',
    descripcion: 'Confirma cierre administrativo, tareas pendientes y siguiente estado.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'C09',
    audiencia: ['profesional'],
    ruta: '/profesional/sala-espera',
    titulo: 'Sala de espera',
    descripcion:
      'Ordena llegadas, prioridad autorizada, demora y ubicación sin exposición innecesaria.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M8',
    prioridad: 'critica',
  },
  {
    id: 'C10',
    audiencia: ['profesional'],
    ruta: '/profesional/sala-espera/llamar',
    titulo: 'Llamar al paciente',
    descripcion: 'Cambia estado y notifica por identificador discreto con alternativa accesible.',
    estadoVisual: 'ST-J',
    responsive: 'RS-Q',
    motion: 'M4',
    prioridad: 'critica',
  },
  {
    id: 'C11',
    audiencia: ['profesional'],
    ruta: '/profesional/agenda/retraso-sobrecita',
    titulo: 'Retraso o sobrecita',
    descripcion: 'Registra motivo, autorización, impacto y comunicación minimizada.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'C12',
    audiencia: ['profesional'],
    ruta: '/profesional/lista-espera',
    titulo: 'Lista de espera profesional',
    descripcion: 'Consulta candidatos elegibles y ofertas sin alterar prioridades autorizadas.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'C13',
    audiencia: ['profesional'],
    ruta: '/profesional/disponibilidad',
    titulo: 'Disponibilidad',
    descripcion: 'Muestra horario efectivo, excepciones y capacidad por unidad y servicio.',
    estadoVisual: 'ST-A',
    responsive: 'RS-C',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'C14',
    audiencia: ['profesional'],
    ruta: '/profesional/disponibilidad/plantilla',
    titulo: 'Plantilla de disponibilidad',
    descripcion: 'Edita bloques recurrentes con vigencia, descansos y recursos.',
    estadoVisual: 'ST-D',
    responsive: 'RS-C',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'C15',
    audiencia: ['profesional'],
    ruta: '/profesional/disponibilidad/excepciones',
    titulo: 'Ausencias y excepciones',
    descripcion: 'Registra cierres, ausencias y sustituciones mostrando citas afectadas.',
    estadoVisual: 'ST-H',
    responsive: 'RS-C',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'C16',
    audiencia: ['profesional'],
    ruta: '/profesional/paciente/contexto',
    titulo: 'Contexto mínimo del paciente',
    descripcion: 'Mantiene banner de paciente, centro, finalidad, relación y restricciones.',
    estadoVisual: 'ST-E',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'C17',
    audiencia: ['profesional'],
    ruta: '/profesional/paciente/citas',
    titulo: 'Historial pertinente de citas',
    descripcion: 'Limita el historial a la relación, especialidad, centro y finalidad activas.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'C18',
    audiencia: ['profesional'],
    ruta: '/profesional/paciente/resumen-administrativo',
    titulo: 'Resumen administrativo',
    descripcion:
      'Muestra contacto y necesidades logísticas estrictamente necesarias para la atención.',
    estadoVisual: 'ST-E',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'C19',
    audiencia: ['profesional'],
    ruta: '/profesional/paciente/medicacion',
    titulo: 'Medicación del paciente',
    descripcion: 'Separa registros validados, declaraciones, históricas y discrepancias.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'C20',
    audiencia: ['profesional'],
    ruta: '/profesional/paciente/medicacion/nueva',
    titulo: 'Registrar medicación',
    descripcion: 'Crea un registro con catálogo, pauta, origen, vigencia y evidencia.',
    estadoVisual: 'ST-D',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'C21',
    audiencia: ['profesional'],
    ruta: '/profesional/paciente/medicacion/detalle',
    titulo: 'Detalle profesional de medicación',
    descripcion: 'Presenta pauta estructurada, autoría, historial y acciones autorizadas.',
    estadoVisual: 'ST-A',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'C22',
    audiencia: ['profesional'],
    ruta: '/profesional/paciente/medicacion/cambiar-pauta',
    titulo: 'Cambiar pauta',
    descripcion: 'Versiona la pauta, exige motivo y previene sobrescritura concurrente.',
    estadoVisual: 'ST-H',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'C23',
    audiencia: ['profesional'],
    ruta: '/profesional/paciente/medicacion/suspender',
    titulo: 'Suspender medicación',
    descripcion: 'Confirma alcance, fecha y motivo conservando historial íntegro.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'C24',
    audiencia: ['profesional'],
    ruta: '/profesional/paciente/medicacion/discrepancias',
    titulo: 'Gestionar discrepancias',
    descripcion: 'Compara fuentes, documenta decisión y asigna revisión sin borrado.',
    estadoVisual: 'ST-H',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'C25',
    audiencia: ['profesional'],
    ruta: '/profesional/paciente/medicacion/conciliar',
    titulo: 'Conciliar medicación',
    descripcion: 'Flujo de comparación y resolución con firma de responsabilidad profesional.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'C26',
    audiencia: ['profesional'],
    ruta: '/profesional/medicacion/renovaciones',
    titulo: 'Solicitudes de renovación',
    descripcion: 'Prioriza solicitudes por estado y contexto sin automatizar decisiones clínicas.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'C27',
    audiencia: ['profesional'],
    ruta: '/profesional/medicacion/renovaciones/revisar',
    titulo: 'Revisar renovación',
    descripcion: 'Muestra solicitud, antecedentes autorizados y resolución trazable.',
    estadoVisual: 'ST-G',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'C28',
    audiencia: ['profesional'],
    ruta: '/profesional/paciente/medicacion/declaraciones',
    titulo: 'Declaraciones del paciente',
    descripcion: 'Revisa información aportada diferenciándola de datos validados.',
    estadoVisual: 'ST-E',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'C29',
    audiencia: ['profesional'],
    ruta: '/profesional/paciente/documentos',
    titulo: 'Espacio documental profesional',
    descripcion: 'Lista borradores, revisiones, firmas, publicaciones y versiones autorizadas.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'C30',
    audiencia: ['profesional'],
    ruta: '/profesional/paciente/documentos/nuevo',
    titulo: 'Crear documento',
    descripcion: 'Selecciona plantilla aprobada, propósito, destinatario y datos mínimos.',
    estadoVisual: 'ST-D',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'C31',
    audiencia: ['profesional'],
    ruta: '/profesional/paciente/documentos/revisar',
    titulo: 'Revisar documento',
    descripcion: 'Compara versión, valida campos y evita edición del documento ya emitido.',
    estadoVisual: 'ST-H',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'C32',
    audiencia: ['profesional'],
    ruta: '/profesional/paciente/documentos/firmar',
    titulo: 'Solicitar o aplicar firma',
    descripcion: 'Expone documento, nivel de firma, proveedor y reautenticación requerida.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'C33',
    audiencia: ['profesional'],
    ruta: '/profesional/paciente/documentos/publicar',
    titulo: 'Publicar o versionar documento',
    descripcion: 'Confirma audiencia, notificación, sustitución y retirada con evidencia.',
    estadoVisual: 'ST-J',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'C34',
    audiencia: ['profesional'],
    ruta: '/profesional/acceso-excepcional',
    titulo: 'Solicitar acceso excepcional',
    descripcion: 'Recoge motivo, finalidad, alcance y duración para un break-glass auditado.',
    estadoVisual: 'ST-K',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },

  {
    id: 'R01',
    audiencia: ['recepcion'],
    ruta: '/recepcion/inicio',
    titulo: 'Inicio de recepción',
    descripcion: 'Resume llegadas, citas próximas, incidencias y tareas administrativas.',
    estadoVisual: 'ST-A',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'R02',
    audiencia: ['recepcion'],
    ruta: '/recepcion/pacientes/buscar',
    titulo: 'Buscar paciente',
    descripcion: 'Consulta minimizada, limitada y auditada con mensajes anti-enumeración.',
    estadoVisual: 'ST-C',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'R03',
    audiencia: ['recepcion'],
    ruta: '/recepcion/pacientes/resultados',
    titulo: 'Resultados de pacientes',
    descripcion: 'Muestra atributos administrativos mínimos y alertas de coincidencia.',
    estadoVisual: 'ST-E',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'R04',
    audiencia: ['recepcion'],
    ruta: '/recepcion/pacientes/nuevo',
    titulo: 'Alta de paciente',
    descripcion: 'Registra identidad, contacto, evidencias y ámbito organizativo.',
    estadoVisual: 'ST-D',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'R05',
    audiencia: ['recepcion'],
    ruta: '/recepcion/pacientes/verificar-identidad',
    titulo: 'Verificar identidad del paciente',
    descripcion: 'Guía comprobaciones, documentos y resultado sin almacenar copias innecesarias.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'R06',
    audiencia: ['recepcion'],
    ruta: '/recepcion/pacientes/posibles-duplicados',
    titulo: 'Posibles duplicados',
    descripcion: 'Compara coincidencias minimizadas y bloquea altas ambiguas.',
    estadoVisual: 'ST-H',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'R07',
    audiencia: ['recepcion'],
    ruta: '/recepcion/pacientes/comparar',
    titulo: 'Comparar duplicados',
    descripcion: 'Alinea campos administrativos, procedencia y conflictos con acceso restringido.',
    estadoVisual: 'ST-H',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'R08',
    audiencia: ['recepcion', 'administracion'],
    ruta: '/recepcion/pacientes/fusion/vista-previa',
    titulo: 'Vista previa de fusión',
    descripcion: 'Expone registro maestro, dependencias, conflictos y plan de reversión.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'R09',
    audiencia: ['recepcion', 'administracion'],
    ruta: '/recepcion/pacientes/fusion/doble-control',
    titulo: 'Doble control de fusión',
    descripcion: 'Requiere segundo aprobador, reautenticación y separación de funciones.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'R10',
    audiencia: ['recepcion', 'administracion'],
    ruta: '/recepcion/pacientes/fusion/resultado',
    titulo: 'Resultado de fusión',
    descripcion: 'Muestra evidencias, incidencias y ventana controlada de reversión.',
    estadoVisual: 'ST-J',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'R11',
    audiencia: ['recepcion'],
    ruta: '/recepcion/pacientes/detalle',
    titulo: 'Ficha administrativa del paciente',
    descripcion: 'Muestra identidad, contacto, representantes y alertas sin datos clínicos.',
    estadoVisual: 'ST-E',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'R12',
    audiencia: ['recepcion'],
    ruta: '/recepcion/pacientes/contacto',
    titulo: 'Actualizar contacto',
    descripcion: 'Cambia datos administrativos con verificación, motivo e historial.',
    estadoVisual: 'ST-D',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'R13',
    audiencia: ['recepcion'],
    ruta: '/recepcion/pacientes/representantes',
    titulo: 'Gestionar representantes',
    descripcion: 'Registra relación, alcance, vigencia y evidencia de representación.',
    estadoVisual: 'ST-G',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'R14',
    audiencia: ['recepcion'],
    ruta: '/recepcion/pacientes/activar-portal',
    titulo: 'Activar portal',
    descripcion: 'Configura invitación, canal verificado, caducidad y estado de activación.',
    estadoVisual: 'ST-I',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'R15',
    audiencia: ['recepcion'],
    ruta: '/recepcion/pacientes/documentos-identidad',
    titulo: 'Documentación identificativa',
    descripcion: 'Gestiona evidencia, vigencia y acceso minimizado con controles de archivo.',
    estadoVisual: 'ST-G',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'R16',
    audiencia: ['recepcion'],
    ruta: '/recepcion/citas',
    titulo: 'Puesto de citas',
    descripcion: 'Busca, filtra y actúa sobre citas por servicio, unidad, recurso y estado.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'R17',
    audiencia: ['recepcion'],
    ruta: '/recepcion/citas/nueva/paciente',
    titulo: 'Elegir paciente para la cita',
    descripcion: 'Vincula el contexto administrativo correcto con verificación previa.',
    estadoVisual: 'ST-E',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'R18',
    audiencia: ['recepcion'],
    ruta: '/recepcion/citas/nueva/servicio',
    titulo: 'Elegir servicio y modalidad',
    descripcion: 'Filtra servicios, modalidades, requisitos y restricciones vigentes del centro.',
    estadoVisual: 'ST-D',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'R19',
    audiencia: ['recepcion'],
    ruta: '/recepcion/citas/nueva/hueco',
    titulo: 'Buscar hueco',
    descripcion: 'Consulta disponibilidad de servidor y ofrece alternativas multi-recurso.',
    estadoVisual: 'ST-H',
    responsive: 'RS-C',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'R20',
    audiencia: ['recepcion'],
    ruta: '/recepcion/citas/nueva/confirmar',
    titulo: 'Confirmar cita administrativa',
    descripcion: 'Revisa alcance, contacto, requisitos y consentimiento de notificación.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'R21',
    audiencia: ['recepcion'],
    ruta: '/recepcion/citas/cambiar',
    titulo: 'Cambiar cita',
    descripcion: 'Mantiene reserva original, compara alternativas y resuelve conflictos.',
    estadoVisual: 'ST-H',
    responsive: 'RS-C',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'R22',
    audiencia: ['recepcion'],
    ruta: '/recepcion/citas/cancelar',
    titulo: 'Cancelar cita desde recepción',
    descripcion: 'Valida autoridad, política, motivo y comunicación al paciente.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'R23',
    audiencia: ['recepcion'],
    ruta: '/recepcion/citas/multiples',
    titulo: 'Crear citas múltiples',
    descripcion: 'Coordina varias reservas con resumen, conflictos y resultado parcial explícito.',
    estadoVisual: 'ST-H',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'R24',
    audiencia: ['recepcion'],
    ruta: '/recepcion/citas/recurrentes',
    titulo: 'Crear citas recurrentes',
    descripcion: 'Define patrón, vigencia, excepciones y estrategia frente a conflictos.',
    estadoVisual: 'ST-H',
    responsive: 'RS-C',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'R25',
    audiencia: ['recepcion'],
    ruta: '/recepcion/citas/recursos',
    titulo: 'Asignar recursos',
    descripcion: 'Reserva sala y equipamiento respetando capacidad, mantenimiento y bloqueos.',
    estadoVisual: 'ST-H',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'R26',
    audiencia: ['recepcion'],
    ruta: '/recepcion/lista-espera',
    titulo: 'Gestionar lista de espera',
    descripcion: 'Consulta solicitudes, criterios, prioridad autorizada y vigencia.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'R27',
    audiencia: ['recepcion'],
    ruta: '/recepcion/lista-espera/ofertas',
    titulo: 'Gestionar ofertas',
    descripcion: 'Envía, caduca y reasigna ofertas con trazabilidad e idempotencia.',
    estadoVisual: 'ST-I',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'R28',
    audiencia: ['recepcion'],
    ruta: '/recepcion/sala-espera',
    titulo: 'Sala de espera de recepción',
    descripcion: 'Coordina llegada, ubicación, prioridad autorizada, demora y salida.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M8',
    prioridad: 'critica',
  },
  {
    id: 'R29',
    audiencia: ['recepcion'],
    ruta: '/recepcion/sala-espera/check-in',
    titulo: 'Registrar llegada',
    descripcion: 'Verifica cita e identidad mínima y registra hora y ubicación.',
    estadoVisual: 'ST-J',
    responsive: 'RS-Q',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'R30',
    audiencia: ['recepcion'],
    ruta: '/recepcion/sala-espera/sin-cita',
    titulo: 'Atención sin cita',
    descripcion: 'Registra una demanda no programada dentro de reglas y capacidad autorizadas.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'R31',
    audiencia: ['recepcion'],
    ruta: '/recepcion/sala-espera/retrasos',
    titulo: 'Gestionar retrasos',
    descripcion: 'Actualiza demora estimada y comunica sin información clínica.',
    estadoVisual: 'ST-I',
    responsive: 'RS-D',
    motion: 'M8',
    prioridad: 'alta',
  },
  {
    id: 'R32',
    audiencia: ['recepcion'],
    ruta: '/recepcion/sala-espera/salida',
    titulo: 'No presentado o salida',
    descripcion: 'Registra transición, motivo administrativo y acciones posteriores.',
    estadoVisual: 'ST-G',
    responsive: 'RS-Q',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'R33',
    audiencia: ['publica', 'recepcion'],
    ruta: '/quiosco/check-in',
    titulo: 'Quiosco de check-in',
    descripcion: 'Flujo táctil, privado y accesible que limpia la sesión tras cada operación.',
    estadoVisual: 'ST-D',
    responsive: 'RS-X',
    motion: 'M3',
    prioridad: 'critica',
  },
  {
    id: 'R34',
    audiencia: ['recepcion'],
    ruta: '/recepcion/citas/recordatorios',
    titulo: 'Recordatorios de cita',
    descripcion: 'Revisa preferencias, entregas fallidas y reenvío seguro sin contenido clínico.',
    estadoVisual: 'ST-I',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'alta',
  },

  {
    id: 'A01',
    audiencia: ['administracion'],
    ruta: '/administracion/inicio',
    titulo: 'Inicio de administración',
    descripcion:
      'Resume configuración pendiente, capacidad, calidad de datos y alertas operativas.',
    estadoVisual: 'ST-A',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'A02',
    audiencia: ['administracion'],
    ruta: '/administracion/organizacion',
    titulo: 'Organización',
    descripcion: 'Gestiona identidad, ámbitos, vigencias y configuración general.',
    estadoVisual: 'ST-D',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'A03',
    audiencia: ['administracion'],
    ruta: '/administracion/centro',
    titulo: 'Configuración del centro',
    descripcion: 'Gestiona el único centro, sus unidades, estado, horario y responsables.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'A04',
    audiencia: ['administracion'],
    ruta: '/administracion/centro/detalle',
    titulo: 'Detalle de centro',
    descripcion: 'Edita datos, vigencia, accesibilidad, contacto y configuración local.',
    estadoVisual: 'ST-D',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'A05',
    audiencia: ['administracion'],
    ruta: '/administracion/espacios',
    titulo: 'Consultas, salas y espacios',
    descripcion: 'Lista espacios con capacidad, ubicación, uso y disponibilidad.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'A06',
    audiencia: ['administracion'],
    ruta: '/administracion/espacios/detalle',
    titulo: 'Detalle de espacio',
    descripcion: 'Gestiona características, asignaciones, accesibilidad y cierres.',
    estadoVisual: 'ST-D',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'A07',
    audiencia: ['administracion'],
    ruta: '/administracion/centro/cierres',
    titulo: 'Cierres y excepciones',
    descripcion: 'Programa cierres y muestra agenda, recursos y pacientes afectados.',
    estadoVisual: 'ST-H',
    responsive: 'RS-C',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'A08',
    audiencia: ['administracion'],
    ruta: '/administracion/servicios',
    titulo: 'Servicios',
    descripcion: 'Administra catálogo, modalidad, unidades, vigencia y requisitos.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'A09',
    audiencia: ['administracion'],
    ruta: '/administracion/servicios/detalle',
    titulo: 'Detalle de servicio',
    descripcion: 'Configura duración, profesionales, recursos, restricciones y publicación.',
    estadoVisual: 'ST-D',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'A10',
    audiencia: ['administracion'],
    ruta: '/administracion/especialidades',
    titulo: 'Especialidades',
    descripcion: 'Mantiene catálogo, vigencia y relación con servicios y profesionales.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'A11',
    audiencia: ['administracion'],
    ruta: '/administracion/tipos-cita',
    titulo: 'Tipos de cita',
    descripcion: 'Define modalidad, duración, preparación, elegibilidad y transiciones.',
    estadoVisual: 'ST-D',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'A12',
    audiencia: ['administracion'],
    ruta: '/administracion/recursos',
    titulo: 'Recursos y equipamiento',
    descripcion:
      'Lista recursos del centro por unidad, capacidad, estado y próxima indisponibilidad.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'A13',
    audiencia: ['administracion'],
    ruta: '/administracion/recursos/detalle',
    titulo: 'Detalle de recurso',
    descripcion: 'Configura capacidad, compatibilidades, vigencia y asignaciones.',
    estadoVisual: 'ST-D',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'A14',
    audiencia: ['administracion'],
    ruta: '/administracion/recursos/mantenimiento',
    titulo: 'Mantenimiento de recursos',
    descripcion: 'Programa bloqueos, responsables y citas afectadas con resolución de conflictos.',
    estadoVisual: 'ST-H',
    responsive: 'RS-C',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'A15',
    audiencia: ['administracion'],
    ruta: '/administracion/profesionales',
    titulo: 'Profesionales',
    descripcion: 'Lista profesionales, identidad, colegiación, unidades, servicios y estado.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'A16',
    audiencia: ['administracion'],
    ruta: '/administracion/profesionales/detalle',
    titulo: 'Detalle de profesional',
    descripcion: 'Gestiona datos profesionales y referencias de identidad sin exponer secretos.',
    estadoVisual: 'ST-D',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'A17',
    audiencia: ['administracion'],
    ruta: '/administracion/profesionales/asignaciones',
    titulo: 'Asignaciones',
    descripcion: 'Relaciona unidades, servicios, roles y vigencias dentro del centro.',
    estadoVisual: 'ST-H',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'A18',
    audiencia: ['administracion'],
    ruta: '/administracion/profesionales/horarios',
    titulo: 'Horarios profesionales',
    descripcion: 'Administra plantillas, capacidad, descansos y recursos necesarios.',
    estadoVisual: 'ST-D',
    responsive: 'RS-C',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'A19',
    audiencia: ['administracion'],
    ruta: '/administracion/profesionales/ausencias',
    titulo: 'Ausencias y sustituciones',
    descripcion: 'Planifica vigencias, sustituto y tratamiento de citas afectadas.',
    estadoVisual: 'ST-H',
    responsive: 'RS-C',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'A20',
    audiencia: ['administracion'],
    ruta: '/administracion/plantillas/notificaciones',
    titulo: 'Plantillas de notificación',
    descripcion: 'Lista canal, idioma, versión, aprobación y categorías autorizadas.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'A21',
    audiencia: ['administracion'],
    ruta: '/administracion/plantillas/notificaciones/editar',
    titulo: 'Editor de notificación',
    descripcion: 'Edita variables permitidas, contenido minimizado y fallback por canal.',
    estadoVisual: 'ST-D',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'A22',
    audiencia: ['administracion'],
    ruta: '/administracion/plantillas/notificaciones/vista-previa',
    titulo: 'Vista previa multicanal',
    descripcion: 'Simula correo, SMS y portal con datos sintéticos y advertencias de privacidad.',
    estadoVisual: 'ST-E',
    responsive: 'RS-P',
    motion: 'M1',
    prioridad: 'alta',
  },
  {
    id: 'A23',
    audiencia: ['administracion'],
    ruta: '/administracion/plantillas/documentos',
    titulo: 'Plantillas documentales',
    descripcion: 'Gestiona tipo, versión, firma, vigencia y estado de aprobación.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'A24',
    audiencia: ['administracion'],
    ruta: '/administracion/plantillas/documentos/editar',
    titulo: 'Editor de plantilla documental',
    descripcion: 'Edita campos permitidos, branding, accesibilidad y previsualización PDF.',
    estadoVisual: 'ST-D',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'A25',
    audiencia: ['administracion'],
    ruta: '/administracion/reglas',
    titulo: 'Reglas de negocio',
    descripcion: 'Inventaría reglas, prioridad, ámbito, vigencia, aprobación e impacto.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'A26',
    audiencia: ['administracion'],
    ruta: '/administracion/reglas/reserva',
    titulo: 'Reglas de reserva',
    descripcion: 'Configura elegibilidad, antelación, duración, simultaneidad y recursos.',
    estadoVisual: 'ST-D',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'A27',
    audiencia: ['administracion'],
    ruta: '/administracion/reglas/cambio-cancelacion',
    titulo: 'Cambio y cancelación',
    descripcion: 'Define ventanas, consecuencias, excepciones y comunicación.',
    estadoVisual: 'ST-D',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'A28',
    audiencia: ['administracion'],
    ruta: '/administracion/reglas/capacidad',
    titulo: 'Capacidad y sobrecitas',
    descripcion: 'Establece límites, autorizadores y alertas por servicio y unidad.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'A29',
    audiencia: ['administracion'],
    ruta: '/administracion/reglas/lista-espera',
    titulo: 'Reglas de lista de espera',
    descripcion: 'Configura criterios, prioridad, vigencia, ofertas y expiración.',
    estadoVisual: 'ST-D',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'A30',
    audiencia: ['administracion'],
    ruta: '/administracion/reglas/documentacion',
    titulo: 'Requisitos documentales',
    descripcion: 'Asocia documentos necesarios por servicio, modalidad y perfil.',
    estadoVisual: 'ST-D',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'A31',
    audiencia: ['administracion'],
    ruta: '/administracion/reglas/restricciones-operativas',
    titulo: 'Restricciones operativas',
    descripcion: 'Define ámbitos por unidad/servicio, excepciones, vigencia y disponibilidad.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'A32',
    audiencia: ['administracion'],
    ruta: '/administracion/calendario-laboral',
    titulo: 'Calendario laboral',
    descripcion: 'Gestiona festivos, cierres y excepciones locales con impacto calculado.',
    estadoVisual: 'ST-H',
    responsive: 'RS-C',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'A33',
    audiencia: ['administracion'],
    ruta: '/administracion/informes',
    titulo: 'Informes operativos',
    descripcion: 'Ofrece indicadores agregados, filtros seguros y exportación controlada.',
    estadoVisual: 'ST-A',
    responsive: 'RS-R',
    motion: 'M1',
    prioridad: 'alta',
  },
  {
    id: 'A34',
    audiencia: ['administracion'],
    ruta: '/administracion/informes/citas',
    titulo: 'Informe de citas',
    descripcion: 'Analiza volumen, estados, cancelaciones y no presentados sin identificadores.',
    estadoVisual: 'ST-A',
    responsive: 'RS-R',
    motion: 'M1',
    prioridad: 'alta',
  },
  {
    id: 'A35',
    audiencia: ['administracion'],
    ruta: '/administracion/informes/espera',
    titulo: 'Informe de tiempos de espera',
    descripcion: 'Compara espera y demora por unidad, servicio y periodo.',
    estadoVisual: 'ST-A',
    responsive: 'RS-R',
    motion: 'M1',
    prioridad: 'alta',
  },
  {
    id: 'A36',
    audiencia: ['administracion'],
    ruta: '/administracion/informes/capacidad',
    titulo: 'Informe de utilización',
    descripcion: 'Mide ocupación de agendas, espacios y recursos con definición visible.',
    estadoVisual: 'ST-A',
    responsive: 'RS-R',
    motion: 'M1',
    prioridad: 'alta',
  },
  {
    id: 'A37',
    audiencia: ['administracion'],
    ruta: '/administracion/informes/lista-espera',
    titulo: 'Informe de lista de espera',
    descripcion: 'Evalúa solicitudes, ofertas, aceptación y tiempo de resolución.',
    estadoVisual: 'ST-A',
    responsive: 'RS-R',
    motion: 'M1',
    prioridad: 'media',
  },
  {
    id: 'A38',
    audiencia: ['administracion'],
    ruta: '/administracion/informes/portal',
    titulo: 'Informe de activación del portal',
    descripcion: 'Muestra invitaciones, activaciones y fallos por canal de forma agregada.',
    estadoVisual: 'ST-A',
    responsive: 'RS-R',
    motion: 'M1',
    prioridad: 'media',
  },
  {
    id: 'A39',
    audiencia: ['administracion'],
    ruta: '/administracion/informes/exportar',
    titulo: 'Exportar informe',
    descripcion: 'Confirma filtros, granularidad, finalidad, destinatario y caducidad.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'A40',
    audiencia: ['administracion'],
    ruta: '/administracion/integraciones',
    titulo: 'Catálogo de integraciones',
    descripcion: 'Lista proveedor, finalidad, datos, estado, propietario y entorno.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'A41',
    audiencia: ['administracion'],
    ruta: '/administracion/integraciones/detalle',
    titulo: 'Detalle de integración',
    descripcion: 'Muestra contrato, capacidades, permisos, SLA y simulador disponible.',
    estadoVisual: 'ST-F',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'A42',
    audiencia: ['administracion'],
    ruta: '/administracion/integraciones/mapeos',
    titulo: 'Mapeo de interoperabilidad',
    descripcion: 'Versiona equivalencias internas, FHIR y catálogos externos con validación.',
    estadoVisual: 'ST-H',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'A43',
    audiencia: ['administracion'],
    ruta: '/administracion/importaciones',
    titulo: 'Importaciones',
    descripcion: 'Controla carga, validación, staging, progreso y rollback.',
    estadoVisual: 'ST-I',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'A44',
    audiencia: ['administracion'],
    ruta: '/administracion/importaciones/reconciliar',
    titulo: 'Reconciliar importación',
    descripcion: 'Revisa coincidencias, conflictos, muestras, aprobación y resultado final.',
    estadoVisual: 'ST-H',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },

  {
    id: 'S01',
    audiencia: ['seguridad', 'auditoria', 'dpd'],
    ruta: '/seguridad/inicio',
    titulo: 'Centro de confianza',
    descripcion:
      'Resume alertas, accesos privilegiados, incidentes, solicitudes y controles vencidos.',
    estadoVisual: 'ST-A',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S02',
    audiencia: ['seguridad'],
    ruta: '/seguridad/usuarios',
    titulo: 'Usuarios',
    descripcion: 'Lista identidades, estado, MFA, último acceso y ámbitos vigentes.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S03',
    audiencia: ['seguridad'],
    ruta: '/seguridad/usuarios/detalle',
    titulo: 'Detalle de usuario',
    descripcion: 'Reúne identidad, asignaciones, autenticadores, sesiones y actividad relevante.',
    estadoVisual: 'ST-E',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S04',
    audiencia: ['seguridad'],
    ruta: '/seguridad/usuarios/invitar',
    titulo: 'Invitar usuario',
    descripcion: 'Define identidad, rol inicial mínimo, ámbito, vigencia y canal verificado.',
    estadoVisual: 'ST-D',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S05',
    audiencia: ['seguridad'],
    ruta: '/seguridad/usuarios/asignar-rol',
    titulo: 'Asignar rol',
    descripcion:
      'Selecciona rol, finalidad, ámbito, vigencia y aprobador sin privilegios absolutos.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S06',
    audiencia: ['seguridad'],
    ruta: '/seguridad/usuarios/asignar-ambito',
    titulo: 'Asignar ámbito',
    descripcion: 'Limita unidad, servicio, finalidad y periodo de acceso dentro del centro fijo.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S07',
    audiencia: ['seguridad'],
    ruta: '/seguridad/usuarios/suspender',
    titulo: 'Suspender o revocar usuario',
    descripcion: 'Expone impacto, revoca sesiones y conserva evidencia con doble control.',
    estadoVisual: 'ST-J',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S08',
    audiencia: ['seguridad'],
    ruta: '/seguridad/sesiones',
    titulo: 'Sesiones de personal',
    descripcion: 'Filtra riesgo, contexto, dispositivo y permite revocación individual o masiva.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S09',
    audiencia: ['seguridad'],
    ruta: '/seguridad/autenticacion/politicas-mfa',
    titulo: 'Políticas MFA',
    descripcion: 'Define obligatoriedad, métodos permitidos, recuperación y step-up por acción.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S10',
    audiencia: ['seguridad'],
    ruta: '/seguridad/autenticacion/metodos',
    titulo: 'Métodos de autenticación',
    descripcion: 'Administra OIDC, passkeys, claves de recuperación y ciclo de vida.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S11',
    audiencia: ['seguridad'],
    ruta: '/seguridad/roles',
    titulo: 'Roles',
    descripcion: 'Lista roles por propósito, riesgo, propietarios, usuarios y vigencia.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S12',
    audiencia: ['seguridad'],
    ruta: '/seguridad/roles/detalle',
    titulo: 'Detalle de rol',
    descripcion: 'Muestra permisos, condiciones ABAC, incompatibilidades y cambios.',
    estadoVisual: 'ST-E',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S13',
    audiencia: ['seguridad', 'auditoria'],
    ruta: '/seguridad/permisos/matriz',
    titulo: 'Matriz de permisos',
    descripcion: 'Cruza rol, recurso, acción, ámbito, finalidad y controles adicionales.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S14',
    audiencia: ['seguridad', 'auditoria'],
    ruta: '/seguridad/certificaciones',
    titulo: 'Campañas de certificación',
    descripcion: 'Planifica revisiones periódicas con propietario, alcance, fecha y evidencia.',
    estadoVisual: 'ST-I',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'S15',
    audiencia: ['seguridad', 'auditoria'],
    ruta: '/seguridad/certificaciones/revisar',
    titulo: 'Revisar accesos',
    descripcion: 'Decide mantener, reducir o revocar cada asignación con justificación.',
    estadoVisual: 'ST-G',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S16',
    audiencia: ['seguridad', 'auditoria'],
    ruta: '/seguridad/separacion-funciones',
    titulo: 'Separación de funciones',
    descripcion: 'Detecta combinaciones incompatibles, excepciones y planes de remediación.',
    estadoVisual: 'ST-H',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S17',
    audiencia: ['seguridad', 'auditoria'],
    ruta: '/seguridad/identidades-privilegiadas',
    titulo: 'Identidades privilegiadas',
    descripcion: 'Supervisa cuentas elevadas, uso, aprobación, vigencia y credenciales.',
    estadoVisual: 'ST-K',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S18',
    audiencia: ['seguridad', 'auditoria'],
    ruta: '/seguridad/break-glass',
    titulo: 'Accesos excepcionales',
    descripcion: 'Lista solicitudes, sesiones activas, expiradas y pendientes de revisión.',
    estadoVisual: 'ST-K',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S19',
    audiencia: ['seguridad'],
    ruta: '/seguridad/break-glass/revisar',
    titulo: 'Revisar acceso excepcional',
    descripcion: 'Evalúa motivo, paciente, finalidad, alcance, reautenticación y urgencia.',
    estadoVisual: 'ST-K',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S20',
    audiencia: ['seguridad', 'auditoria', 'dpd'],
    ruta: '/seguridad/break-glass/timeline',
    titulo: 'Cronología break-glass',
    descripcion: 'Reconstruye solicitud, consultas, acciones, caducidad y revisión posterior.',
    estadoVisual: 'ST-K',
    responsive: 'RS-T',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S21',
    audiencia: ['seguridad', 'soporte'],
    ruta: '/seguridad/soporte-temporal',
    titulo: 'Accesos temporales de soporte',
    descripcion: 'Lista tickets, consentimiento, permisos reducidos y caducidad.',
    estadoVisual: 'ST-K',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S22',
    audiencia: ['seguridad', 'soporte'],
    ruta: '/seguridad/soporte-temporal/nuevo',
    titulo: 'Solicitar acceso de soporte',
    descripcion: 'Define ticket, finalidad técnica, datos mínimos, aprobador y duración.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S23',
    audiencia: ['soporte', 'seguridad'],
    ruta: '/seguridad/soporte-temporal/sesion',
    titulo: 'Sesión temporal de soporte',
    descripcion: 'Mantiene banner persistente, alcance reducido, tiempo restante y cierre.',
    estadoVisual: 'ST-K',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S24',
    audiencia: ['auditoria', 'seguridad', 'dpd'],
    ruta: '/seguridad/auditoria',
    titulo: 'Explorador de auditoría',
    descripcion: 'Filtra eventos por actor, acción, objeto, finalidad, contexto y correlación.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S25',
    audiencia: ['auditoria', 'seguridad', 'dpd'],
    ruta: '/seguridad/auditoria/evento',
    titulo: 'Detalle de evento de auditoría',
    descripcion: 'Muestra metadatos minimizados, resultado, hash y cadena de correlación.',
    estadoVisual: 'ST-E',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S26',
    audiencia: ['auditoria', 'seguridad'],
    ruta: '/seguridad/auditoria/integridad',
    titulo: 'Integridad de auditoría',
    descripcion: 'Verifica cadena criptográfica, anclajes, lag y cualquier discontinuidad.',
    estadoVisual: 'ST-J',
    responsive: 'RS-R',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S27',
    audiencia: ['auditoria', 'seguridad', 'dpd'],
    ruta: '/seguridad/auditoria/exportar',
    titulo: 'Exportar auditoría',
    descripcion: 'Exige finalidad, filtros, aprobación, formato, cifrado y caducidad.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S28',
    audiencia: ['dpd', 'auditoria'],
    ruta: '/privacidad/inicio',
    titulo: 'Panel de privacidad',
    descripcion: 'Resume derechos, restricciones, accesos, retención, EIPD y plazos.',
    estadoVisual: 'ST-A',
    responsive: 'RS-R',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S29',
    audiencia: ['dpd'],
    ruta: '/privacidad/solicitudes',
    titulo: 'Solicitudes de interesados',
    descripcion: 'Prioriza casos por derecho, plazo, identidad, ámbito y estado.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S30',
    audiencia: ['dpd'],
    ruta: '/privacidad/solicitudes/detalle',
    titulo: 'Expediente de derecho',
    descripcion: 'Reúne identidad, alcance, búsqueda, decisiones, comunicaciones y entrega.',
    estadoVisual: 'ST-I',
    responsive: 'RS-T',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S31',
    audiencia: ['dpd', 'seguridad'],
    ruta: '/privacidad/restricciones',
    titulo: 'Gestión de restricciones',
    descripcion: 'Administra alcance, vigencia, excepciones, alertas y efecto en autorizaciones.',
    estadoVisual: 'ST-G',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S32',
    audiencia: ['dpd', 'auditoria'],
    ruta: '/privacidad/transparencia-accesos',
    titulo: 'Casos de transparencia de accesos',
    descripcion: 'Investiga preguntas sobre accesos y prepara respuestas verificables.',
    estadoVisual: 'ST-I',
    responsive: 'RS-T',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'S33',
    audiencia: ['dpd', 'administracion'],
    ruta: '/privacidad/retencion',
    titulo: 'Políticas de retención',
    descripcion: 'Versiona regla, categoría, jurisdicción, inicio, plazo y disposición.',
    estadoVisual: 'ST-G',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S34',
    audiencia: ['dpd', 'seguridad'],
    ruta: '/privacidad/bloqueo-legal',
    titulo: 'Bloqueo legal',
    descripcion: 'Impide disposición por expediente con alcance, autoridad y revisión.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S35',
    audiencia: ['dpd', 'administracion'],
    ruta: '/privacidad/disposicion',
    titulo: 'Disposición y anonimización',
    descripcion: 'Controla candidatos, excepciones, doble aprobación, ejecución y evidencia.',
    estadoVisual: 'ST-I',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S36',
    audiencia: ['dpd'],
    ruta: '/privacidad/bases-juridicas',
    titulo: 'Bases jurídicas y decisiones',
    descripcion: 'Mantiene finalidad, base, categorías, destinatarios y textos asociados.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'S37',
    audiencia: ['dpd'],
    ruta: '/privacidad/rat',
    titulo: 'Registro de actividades',
    descripcion: 'Gestiona tratamientos, finalidades, datos, sistemas, encargados y medidas.',
    estadoVisual: 'ST-D',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S38',
    audiencia: ['dpd', 'seguridad'],
    ruta: '/privacidad/eipd',
    titulo: 'Registro de EIPD',
    descripcion: 'Controla alcance, riesgos, medidas, riesgo residual, consulta y revisión.',
    estadoVisual: 'ST-I',
    responsive: 'RS-R',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S39',
    audiencia: ['dpd', 'seguridad', 'administracion'],
    ruta: '/privacidad/catalogo-datos',
    titulo: 'Catálogo y clasificación de datos',
    descripcion: 'Mapea categorías, sensibilidad, flujos, propietarios, retención y cifrado.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S40',
    audiencia: ['seguridad', 'dpd'],
    ruta: '/seguridad/incidentes',
    titulo: 'Incidentes',
    descripcion: 'Resume severidad, estado, activos, datos, responsables y plazos legales.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M8',
    prioridad: 'critica',
  },
  {
    id: 'S41',
    audiencia: ['seguridad', 'dpd'],
    ruta: '/seguridad/incidentes/detalle',
    titulo: 'Detalle de incidente',
    descripcion: 'Coordina análisis, impacto, contención, comunicaciones y decisiones.',
    estadoVisual: 'ST-I',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S42',
    audiencia: ['seguridad', 'dpd', 'auditoria'],
    ruta: '/seguridad/incidentes/timeline',
    titulo: 'Cronología de incidente',
    descripcion: 'Registra hechos, evidencias, acciones, responsables y aprobaciones.',
    estadoVisual: 'ST-I',
    responsive: 'RS-T',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S43',
    audiencia: ['seguridad', 'auditoria'],
    ruta: '/seguridad/incidentes/evidencias',
    titulo: 'Custodia de evidencias',
    descripcion: 'Gestiona hash, origen, acceso, cadena de custodia y exportación.',
    estadoVisual: 'ST-G',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S44',
    audiencia: ['seguridad'],
    ruta: '/seguridad/alertas',
    titulo: 'Alertas de seguridad',
    descripcion: 'Prioriza señales por severidad, confianza, activo, estado y SLA.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M8',
    prioridad: 'critica',
  },
  {
    id: 'S45',
    audiencia: ['seguridad', 'auditoria'],
    ruta: '/seguridad/alertas/investigar',
    titulo: 'Investigar anomalía',
    descripcion: 'Correlaciona eventos, sesiones y contexto minimizado con decisiones trazables.',
    estadoVisual: 'ST-H',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S46',
    audiencia: ['seguridad', 'administracion'],
    ruta: '/operaciones/integraciones',
    titulo: 'Salud de integraciones',
    descripcion: 'Muestra disponibilidad, latencia, errores, reintentos, colas y SLA.',
    estadoVisual: 'ST-F',
    responsive: 'RS-R',
    motion: 'M8',
    prioridad: 'alta',
  },
  {
    id: 'S47',
    audiencia: ['seguridad', 'administracion'],
    ruta: '/operaciones/integraciones/detalle',
    titulo: 'Operación de integración',
    descripcion: 'Gestiona DLQ, reproceso idempotente, circuit breaker y trazas sanitizadas.',
    estadoVisual: 'ST-I',
    responsive: 'RS-W',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S48',
    audiencia: ['seguridad'],
    ruta: '/operaciones/credenciales-integracion',
    titulo: 'Credenciales de integración',
    descripcion:
      'Supervisa referencias de secreto, certificados, rotación y caducidad sin revelar valores.',
    estadoVisual: 'ST-G',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S49',
    audiencia: ['seguridad', 'administracion'],
    ruta: '/operaciones/sistema',
    titulo: 'Estado del sistema',
    descripcion: 'Resume componentes, dependencias, colas, almacenamiento y modo degradado.',
    estadoVisual: 'ST-F',
    responsive: 'RS-R',
    motion: 'M8',
    prioridad: 'critica',
  },
  {
    id: 'S50',
    audiencia: ['seguridad', 'administracion'],
    ruta: '/operaciones/contingencia',
    titulo: 'Activar contingencia',
    descripcion: 'Expone criterio, alcance, procedimientos alternativos, comunicaciones y retorno.',
    estadoVisual: 'ST-G',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S51',
    audiencia: ['seguridad', 'auditoria'],
    ruta: '/operaciones/backups',
    titulo: 'Estado de copias',
    descripcion: 'Muestra cobertura, cifrado, inmutabilidad, antigüedad y fallos sin contenido.',
    estadoVisual: 'ST-A',
    responsive: 'RS-R',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S52',
    audiencia: ['seguridad', 'auditoria'],
    ruta: '/operaciones/restauraciones',
    titulo: 'Pruebas de restauración',
    descripcion: 'Registra alcance, RPO/RTO, resultado, evidencia y acciones correctivas.',
    estadoVisual: 'ST-I',
    responsive: 'RS-T',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S53',
    audiencia: ['seguridad', 'auditoria'],
    ruta: '/informes/seguridad',
    titulo: 'Informes de seguridad',
    descripcion: 'Analiza MFA, sesiones, denegaciones, privilegios, anomalías e incidentes.',
    estadoVisual: 'ST-A',
    responsive: 'RS-R',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'S54',
    audiencia: ['dpd', 'auditoria'],
    ruta: '/informes/privacidad',
    titulo: 'Informes de privacidad',
    descripcion: 'Mide derechos, accesos, restricciones, retención y plazos con agregación.',
    estadoVisual: 'ST-A',
    responsive: 'RS-R',
    motion: 'M0',
    prioridad: 'alta',
  },
  {
    id: 'S55',
    audiencia: ['auditoria', 'seguridad', 'dpd'],
    ruta: '/cumplimiento/evidencias',
    titulo: 'Matriz de evidencias',
    descripcion: 'Mapea controles ASVS, RGPD, ENS y políticas a pruebas y propietarios.',
    estadoVisual: 'ST-A',
    responsive: 'RS-D',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'S56',
    audiencia: ['seguridad', 'auditoria', 'dpd', 'administracion'],
    ruta: '/cumplimiento/salida-produccion',
    titulo: 'Puerta de salida a producción',
    descripcion: 'Bloquea el lanzamiento hasta resolver controles, EIPD, pentest y aprobaciones.',
    estadoVisual: 'ST-J',
    responsive: 'RS-K',
    motion: 'M0',
    prioridad: 'critica',
  },

  {
    id: 'O01',
    audiencia: ['paciente', 'representante', 'profesional', 'recepcion', 'administracion'],
    ruta: 'overlay://confirmar-accion',
    titulo: 'Confirmar acción',
    descripcion: 'Resume objetivo y efecto para una acción reversible sin generar fatiga.',
    estadoVisual: 'ST-G',
    responsive: 'RS-Q',
    motion: 'M5',
    prioridad: 'alta',
  },
  {
    id: 'O02',
    audiencia: ['profesional', 'recepcion', 'administracion', 'seguridad'],
    ruta: 'overlay://confirmar-accion-irreversible',
    titulo: 'Confirmar acción irreversible',
    descripcion: 'Exige frase de confirmación, consecuencias, alternativa y auditoría.',
    estadoVisual: 'ST-J',
    responsive: 'RS-Q',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'O03',
    audiencia: [
      'paciente',
      'representante',
      'profesional',
      'recepcion',
      'administracion',
      'seguridad',
    ],
    ruta: 'overlay://reautenticar',
    titulo: 'Reautenticar',
    descripcion: 'Solicita step-up con contexto de la acción y método resistente a phishing.',
    estadoVisual: 'ST-G',
    responsive: 'RS-Q',
    motion: 'M5',
    prioridad: 'critica',
  },
  {
    id: 'O04',
    audiencia: [
      'paciente',
      'representante',
      'profesional',
      'recepcion',
      'administracion',
      'seguridad',
    ],
    ruta: 'overlay://caducidad-sesion',
    titulo: 'Caducidad de sesión',
    descripcion: 'Muestra tiempo restante, continuidad segura y cierre inmediato.',
    estadoVisual: 'ST-G',
    responsive: 'RS-Q',
    motion: 'M5',
    prioridad: 'critica',
  },
  {
    id: 'O05',
    audiencia: ['paciente', 'representante', 'profesional', 'recepcion', 'administracion'],
    ruta: 'overlay://cambios-sin-guardar',
    titulo: 'Cambios sin guardar',
    descripcion: 'Permite continuar editando o descartar sin guardar borradores sensibles.',
    estadoVisual: 'ST-D',
    responsive: 'RS-Q',
    motion: 'M5',
    prioridad: 'alta',
  },
  {
    id: 'O06',
    audiencia: ['paciente', 'representante', 'profesional', 'recepcion'],
    ruta: 'overlay://conflicto-cita',
    titulo: 'Conflicto de cita',
    descripcion: 'Explica que el hueco cambió y ofrece alternativas frescas del servidor.',
    estadoVisual: 'ST-H',
    responsive: 'RS-Q',
    motion: 'M5',
    prioridad: 'critica',
  },
  {
    id: 'O07',
    audiencia: ['paciente', 'representante', 'recepcion'],
    ruta: 'overlay://reserva-temporal',
    titulo: 'Reserva temporal de hueco',
    descripcion: 'Muestra cuenta atrás accesible, expiración y renovación permitida.',
    estadoVisual: 'ST-H',
    responsive: 'RS-Q',
    motion: 'M4',
    prioridad: 'critica',
  },
  {
    id: 'O08',
    audiencia: [
      'paciente',
      'representante',
      'profesional',
      'recepcion',
      'administracion',
      'seguridad',
    ],
    ruta: 'overlay://acceso-denegado',
    titulo: 'Acceso denegado',
    descripcion: 'Informa sin revelar el recurso y devuelve el foco a una acción segura.',
    estadoVisual: 'ST-E',
    responsive: 'RS-Q',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'O09',
    audiencia: ['profesional', 'seguridad'],
    ruta: 'overlay://motivo-break-glass',
    titulo: 'Motivo de acceso excepcional',
    descripcion: 'Recoge justificación, finalidad, alcance y tiempo antes de continuar.',
    estadoVisual: 'ST-K',
    responsive: 'RS-Q',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'O10',
    audiencia: ['paciente', 'representante', 'administracion', 'auditoria', 'dpd'],
    ruta: 'overlay://alcance-exportacion',
    titulo: 'Alcance de exportación',
    descripcion: 'Confirma categorías, registros, formato, finalidad, destinatario y caducidad.',
    estadoVisual: 'ST-G',
    responsive: 'RS-Q',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'O11',
    audiencia: ['paciente', 'representante', 'profesional', 'recepcion', 'administracion'],
    ruta: 'overlay://subida-segura',
    titulo: 'Subida y análisis de archivo',
    descripcion: 'Muestra límites, progreso, antivirus, rechazo y eliminación segura.',
    estadoVisual: 'ST-I',
    responsive: 'RS-Q',
    motion: 'M5',
    prioridad: 'critica',
  },
  {
    id: 'O12',
    audiencia: [
      'paciente',
      'representante',
      'profesional',
      'recepcion',
      'administracion',
      'seguridad',
    ],
    ruta: 'overlay://proceso-asincrono',
    titulo: 'Proceso en curso',
    descripcion: 'Informa cola, progreso fiable, resultado parcial y forma de volver.',
    estadoVisual: 'ST-I',
    responsive: 'RS-Q',
    motion: 'M4',
    prioridad: 'alta',
  },
  {
    id: 'O13',
    audiencia: ['paciente', 'representante', 'profesional', 'recepcion', 'administracion'],
    ruta: 'overlay://fallo-red',
    titulo: 'Fallo de red',
    descripcion: 'Distingue estado desconocido de fallo confirmado y evita doble envío.',
    estadoVisual: 'ST-F',
    responsive: 'RS-Q',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'O14',
    audiencia: ['profesional', 'recepcion', 'administracion', 'seguridad', 'auditoria', 'dpd'],
    ruta: 'overlay://cambiar-contexto',
    titulo: 'Cambiar contexto',
    descripcion: 'Confirma unidad, servicio, rol y finalidad; el centro permanece fijo.',
    estadoVisual: 'ST-G',
    responsive: 'RS-Q',
    motion: 'M0',
    prioridad: 'critica',
  },
  {
    id: 'O15',
    audiencia: ['profesional', 'recepcion', 'administracion', 'seguridad'],
    ruta: 'overlay://conflicto-edicion',
    titulo: 'Conflicto de edición',
    descripcion: 'Compara versión local y remota y fuerza una resolución explícita.',
    estadoVisual: 'ST-H',
    responsive: 'RS-Q',
    motion: 'M0',
    prioridad: 'critica',
  },
] as const satisfies readonly ScreenDefinition[];

export const screenCatalogCount = screenCatalog.length;

export const mockupRouteFor = (screen: ScreenDefinition): `/mockups/${Lowercase<ScreenId>}` =>
  `/mockups/${screen.id.toLowerCase()}` as `/mockups/${Lowercase<ScreenId>}`;
